AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model as we will be using transfer learning
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 3
CLASSES: 2  #one for Coccidiosis disease and one for healthy
WEIGHTS: imagenet
LEARNING_RATE: 0.01
